package no.goodtech.vaadin.buttons.export;


import com.vaadin.icons.VaadinIcons;
import com.vaadin.server.Resource;
import com.vaadin.ui.Button;
import no.goodtech.vaadin.lists.MessyGrid;
import no.goodtech.vaadin.lists.v7.MessyTable;
import no.goodtech.vaadin.main.ApplicationResourceBundle;

public class CsvExportButton extends Button {
	private static final String BUTTON_CAPTION = ApplicationResourceBundle.getInstance("vaadin-core").getString("button.csvExport");

	private String reportCaption;
	private String exportFileName;

	public CsvExportButton(final MessyGrid table, String reportTitle) {
		this(table, reportTitle, "Table-Export", BUTTON_CAPTION);
	}

	/**
	 * Columns that are generated by a ColumnGenerator have to be changed to
	 *
	 * @param table          with values
	 * @param reportTitle    title of CSV export
	 * @param exportFileName CSV file name (input is without .csv)
	 * @param caption        caption for the Button
	 */
	public CsvExportButton(final MessyGrid table, final String reportTitle, final String exportFileName, final String
			caption) {
		setCaption(caption);
		setIcon(VaadinIcons.FILE_CODE);


		addClickListener((Button.ClickListener) clickEvent -> {
			CsvExportCustomDelimiter csvExport = new CsvExportCustomDelimiter(table);
//TODO: Kræsjer: Se T+ 10190		csvExport.excludeCollapsedColumns();
			csvExport.setDisplayTotals(false);
			csvExport.setReportTitle(reportTitle);
			csvExport.setExportFileName(exportFileName + ".csv");
			csvExport.setDateDataFormat(table.getDateFormatter().toPattern());
			csvExport.setDoubleDataFormat(table.getDecimalFormatter().toPattern());
			csvExport.export();
		});
	}

	@Deprecated
	public CsvExportButton(final MessyTable table, String reportTitle) {
		this(table, reportTitle, "Table-Export", BUTTON_CAPTION);
	}

	/**
	 * Columns that are generated by a ColumnGenerator have to be changed to
	 *
	 * @param table          with values
	 * @param reportTitle    title of CSV export
	 * @param exportFileName CSV file name (input is without .csv)
	 * @param caption        caption for the Button
	 */
	@Deprecated
	public CsvExportButton(final MessyTable table, final String reportTitle, final String exportFileName, final String caption) {
		setCaption(caption);
		setIcon(VaadinIcons.FILE_CODE);

		addClickListener((Button.ClickListener) clickEvent -> {
			no.goodtech.vaadin.buttons.export.v7.CsvExportCustomDelimiter csvExport = new no.goodtech.vaadin.buttons.export.v7.CsvExportCustomDelimiter(table);
			csvExport.excludeCollapsedColumns();
			csvExport.setDisplayTotals(false);
			csvExport.setReportTitle(reportTitle);
			csvExport.setExportFileName(exportFileName + ".csv");
			csvExport.setDateDataFormat(table.getDateFormatter().toPattern());
			csvExport.setDoubleDataFormat(table.getDecimalFormatter().toPattern());
			csvExport.export();
		});
	}


	public String getReportCaption() {
		return reportCaption;
	}

	public void setReportCaption(String reportCaption) {
		this.reportCaption = reportCaption;
	}

	public String getExportFileName() {
		return exportFileName;
	}

	public void setExportFileName(String exportFileName) {
		this.exportFileName = exportFileName;
	}
}
