# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        maven-version: '3.6.3'
        #cache: maven
    - name: Build with Maven
      #run: mvn -B package --file pom.xml
      #run: mvn clean install -e -DskipTests
      run: cd unger-vaadin-core;echo "hello";echo "test1";pwd;echo "test2";dir ../;echo "hvordan gikk det?";echo "test3";ls ~/.m2/;echo "test3"; echo "heisann" >> hoho;ls;echo "gikk det?";less hoho;ls -la ~/.m2/;pwd;echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><settings xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd\"		  xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"		  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">	<servers>		<server>			<id>site-server</id>			<username>apache</username>			<password>cronus1234</password>		</server>	</servers>	<profiles>		<profile>			<repositories>				<repository>					<snapshots>						<enabled>false</enabled>					</snapshots>					<id>libs-release</id>					<name>libs-release</name>					<url>http://1ccf-109-247-50-146.ngrok.io/artifactory/libs-release</url>				</repository>				<repository>					<snapshots/>					<id>libs-snapshot</id>					<name>libs-snapshot</name>					<url>http://1ccf-109-247-50-146.ngrok.io/artifactory/libs-snapshot</url>				</repository>			</repositories>			<pluginRepositories>				<pluginRepository>					<snapshots>						<enabled>false</enabled>					</snapshots>					<id>plugins-release</id>					<name>plugins-release</name>					<url>http://1ccf-109-247-50-146.ngrok.io/artifactory/plugins-release</url>				</pluginRepository>				<pluginRepository>					<snapshots/>					<id>plugins-snapshot</id>					<name>plugins-snapshot</name>					<url>http://1ccf-109-247-50-146.ngrok.io/artifactory/plugins-snapshot</url>				</pluginRepository>			</pluginRepositories>			<id>artifactory</id>		</profile>	</profiles>	<activeProfiles>		<activeProfile>artifactory</activeProfile>	</activeProfiles></settings>" >> settings.xml;ls;cp settings.xml ~/.m2/.;echo "ready! go!";less settings.xml;echo "og i m2?";less ~/.m2/settings.xml;echo "-----"; mvn -version;echo "hehe";ls /usr/share/ 
